### ISSUE TITLE
Fails with "Got an error when updating our internal database."

### ISSUE THREAD

**Issue by kit-ty-kate** [dinosaure/pasteur#16]
Got this popup when trying to upload something to https://paste.osau.re/

**Comment by kit-ty-kate** [comment]
this looks fixed now but i’ll let you close it

**Comment by dinosaure** [comment]
Yes the error appeared on my server because I upgraded `ssh` which disallowed `rsa-sha` keys. I fixed the specific issue on my server and now everything should be fine. Thanks to notice me!
